# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f790d1812207d33d4b508f2768c40bcc3d38f90856796cead9fea340333c2c442e1d2b45856aea4bbefc30b07ae81b687d3b55391a472239889e143aa5059be9

test:
  secret_key_base: dddf85ee6233e8ff9ade449e18e2328b0c62d2368bd6bf199018c1a41d4bdb4d68c979a1b52cb8376a39f3e595ae377dab93e36218fb4ca41c1b084a8e6a23dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
